language: cpp

dist: bionic

# This is clang on macOS
compiler: gcc

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libglew-dev
      - freeglut3-dev
      - libxi-dev
      - libxmu-dev
      - xserver-xorg-video-dummy
      - xpra
      - xorg-dev
      - opencl-headers
      - libgl1-mesa-dev
      - libxcursor-dev
      - libpulse-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxv-dev
      - libasound2-dev
      - libudev-dev
      - mesa-utils
      - libgl1-mesa-glx

jobs:
  include:
    - os: linux
      env:
    - os: osx
      env:

script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - ./bin/unit_test
